-- DB
DROP DATABASE IF EXISTS OnlineStore;
CREATE DATABASE OnlineStore;
SELECT DATABASE OnlineStore;

-- Tables
CREATE TABLE Gender(
    GENDERID BIGINT NOT NULL AUTO_INCREMENT,
    GenderName VARCHAR(255) NOT NULL,
    PRIMARY KEY(GENDERID)
);

CREATE TABLE ProductImage(
    IMAGEID BIGINT NOT NULL AUTO_INCREMENT,
    ImageName TEXT NOT NULL,
    PRIMARY KEY(IMAGEID)
);

CREATE TABLE Brand(
    BRANDID BIGINT NOT NULL AUTO_INCREMENT,
    BrandName VARCHAR(255) NOT NULL,
    PRIMARY KEY(BRANDID)
);

CREATE TABLE Color(
    COLORID BIGINT NOT NULL AUTO_INCREMENT,
    ColorName VARCHAR(255) NOT NULL,
    PRIMARY KEY(COLORID)
);

CREATE TABLE ProductType(
    TYPEID BIGINT NOT NULL AUTO_INCREMENT,
    TypeName VARCHAR(255) NOT NULL,

    PRIMARY KEY(TYPEID)
);

CREATE TABLE Product(
    PRODUCTID BIGINT NOT NULL AUTO_INCREMENT,
    ProductName VARCHAR(255) NOT NULL,
    ProductDescription TEXT,
    DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    COLORID BIGINT NOT NULL,
    BRANDID BIGINT NOT NULL,
    IMAGEID BIGINT NOT NULL,
    TYPEID  BIGINT NOT NULL,

    PRIMARY KEY(PRODUCTID),
    FOREIGN KEY (COLORID) REFERENCES Color(COLORID),
    FOREIGN KEY (BRANDID) REFERENCES Brand(BRANDID),
    FOREIGN KEY (IMAGEID) REFERENCES ProductImage(IMAGEID),
    FOREIGN KEY (TYPEID) REFERENCES ProductType(TYPEID)
);

CREATE TABLE User(
    USERID BIGINT NOT NULL AUTO_INCREMENT,
    LastName VARCHAR(255) NOT NULL,
    FirstName VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    BirthDate DATE NOT NULL,
    LastLogin TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    GENDERID BIGINT NOT NULL,

    PRIMARY KEY(USERID),
    FOREIGN KEY (GENDERID) REFERENCES Gender(GENDERID)
);


CREATE TABLE Wishlist(
    WISHLISTID BIGINT NOT NULL AUTO_INCREMENT,
    DateAdded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRODUCTID BIGINT NOT NULL,
    USERID BIGINT NOT NULL,

    PRIMARY KEY(WISHLISTID),
    FOREIGN KEY (PRODUCTID) REFERENCES Product(PRODUCTID),
    FOREIGN KEY (USERID) REFERENCES User(USERID)
);

CREATE TABLE Cart(
    CARTID BIGINT NOT NULL AUTO_INCREMENT,
    DateAdded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRODUCTID BIGINT NOT NULL,
    USERID BIGINT NOT NULL,

    PRIMARY KEY(CARTID),
    FOREIGN KEY (PRODUCTID) REFERENCES Product(PRODUCTID),
    FOREIGN KEY (USERID) REFERENCES User(USERID)
);

CREATE TABLE ImageProduct(
    IMAGEID BIGINT NOT NULL,
    PRODUCTID BIGINT NOT NULL,

    PRIMARY KEY(IMAGEID, PRODUCTID),
    FOREIGN KEY (IMAGEID) REFERENCES ProductImage(IMAGEID),
    FOREIGN KEY (PRODUCTID) REFERENCES Product(PRODUCTID)
);
-- Index
CREATE UNIQUE INDEX UK_Email
ON User (Email);

CREATE INDEX FK_Product
ON Product (COLORID, BRANDID, IMAGEID, TYPEID);

CREATE INDEX FK_User
ON User (GENDERID);

CREATE INDEX FK_Wishlist
ON Wishlist (PRODUCTID, USERID);

CREATE INDEX FK_Cart
ON Cart (PRODUCTID, USERID);

CREATE INDEX FK_ImageProduct
ON ImageProduct (IMAGEID, PRODUCTID);