-- DB
DROP DATABASE IF EXISTS `NewOnlineStore`;

-- Create DB
CREATE DATABASE IF NOT EXISTS `NewOnlineStore`
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
SET default_storage_engine = INNODB;
USE OnlineStore;

-- Tables
CREATE TABLE pImage(
    IMAGEID     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    iName        VARCHAR(255) NOT NULL,
    Alt         TEXT,
    Title       TEXT,
    PRIMARY KEY(IMAGEID)
);

CREATE TABLE Gender(
    GENDERID    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    gName        VARCHAR(255) NOT NULL,
    PRIMARY KEY(GENDERID)
);

CREATE TABLE Size(
    SIZEID      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Size        DECIMAL(3,1) NOT NULL,
    PRIMARY KEY(SIZEID)
);

CREATE TABLE Color(
    COLORID     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    cName        VARCHAR(255) NOT NULL,
    Hex         BINARY(3) NOT NULL,
    PRIMARY KEY (COLORID)
);

CREATE TABLE Brand(
    BRANDID     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    bName        VARCHAR(255) NOT NULL,
    PRIMARY KEY(BRANDID)
);

CREATE TABLE pType(
    TYPEID      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tName        VARCHAR(255) NOT NULL,

    PRIMARY KEY(TYPEID)
);

CREATE TABLE User(
    USERID      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    LastName    VARCHAR(255) NOT NULL,
    FirstName   VARCHAR(255) NOT NULL,
    Email       VARCHAR(255) NOT NULL,
    Password    VARCHAR(255) NOT NULL,
    BirthDate   DATE NOT NULL,
    LastLogin   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Phone       CHAR(10),
    Admin       BOOL NOT NULL DEFAULT 0,

    GENDERID BIGINT UNSIGNED NOT NULL,

    PRIMARY KEY(USERID),
    FOREIGN KEY (GENDERID) REFERENCES Gender(GENDERID)
);

CREATE TABLE Product(
    PRODUCTID   BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    pName        VARCHAR(255) NOT NULL,
    pDescription TEXT,
    Price       DECIMAL(12,2) NOT NULL,
    DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Listed      BOOLEAN NOT NULL,

    BRANDID     BIGINT UNSIGNED NOT NULL,
    TYPEID      BIGINT UNSIGNED NOT NULL,
    GENDERID    BIGINT UNSIGNED NOT NULL,

    PRIMARY KEY(PRODUCTID),
    FOREIGN KEY (BRANDID) REFERENCES Brand(BRANDID),
    FOREIGN KEY (TYPEID) REFERENCES pType(TYPEID),
    FOREIGN KEY (GENDERID) REFERENCES Gender(GENDERID)
);

CREATE TABLE Wishlist(
    WISHLISTID  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    PRODUCTID   BIGINT UNSIGNED NOT NULL,
    USERID      BIGINT UNSIGNED NOT NULL,
    COLORID     BIGINT UNSIGNED NOT NULL,
    SIZEID      BIGINT UNSIGNED NOT NULL,
    DateAdded   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (WISHLISTID),
    FOREIGN KEY (PRODUCTID) REFERENCES Product(PRODUCTID),
    FOREIGN KEY (USERID) REFERENCES User(USERID),
    FOREIGN KEY (COLORID) REFERENCES Color(COLORID),
    FOREIGN KEY (SIZEID) REFERENCES Size(SIZEID)
);

CREATE TABLE Cart(
    CARTID      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    PRODUCTID   BIGINT UNSIGNED NOT NULL,
    USERID      BIGINT UNSIGNED NOT NULL,
    COLORID     BIGINT UNSIGNED NOT NULL,
    SIZEID      BIGINT UNSIGNED NOT NULL,
    DateAdded   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (CARTID),
    FOREIGN KEY (PRODUCTID) REFERENCES Product(PRODUCTID),
    FOREIGN KEY (USERID) REFERENCES User(USERID),
    FOREIGN KEY (COLORID) REFERENCES Color(COLORID),
    FOREIGN KEY (SIZEID) REFERENCES Size(SIZEID)
);

CREATE TABLE Color_Product(
    COLORID BIGINT UNSIGNED NOT NULL,
    PRODUCTID BIGINT UNSIGNED NOT NULL,

    PRIMARY KEY (COLORID, PRODUCTID),
    FOREIGN KEY (COLORID) REFERENCES Color(COLORID),
    FOREIGN KEY (PRODUCTID) REFERENCES Product(PRODUCTID)
);

CREATE TABLE pImage_Product(
    IMAGEID BIGINT UNSIGNED NOT NULL,
    PRODUCTID BIGINT UNSIGNED NOT NULL,

    PRIMARY KEY(IMAGEID, PRODUCTID),
    FOREIGN KEY (IMAGEID) REFERENCES pImage(IMAGEID),
    FOREIGN KEY (PRODUCTID) REFERENCES Product(PRODUCTID)
);

CREATE TABLE Size_Product(
    SIZEID BIGINT UNSIGNED NOT NULL,
    PRODUCTID BIGINT UNSIGNED NOT NULL,

    PRIMARY KEY (SIZEID, PRODUCTID),
    FOREIGN KEY (SIZEID) REFERENCES Size(SIZEID),
    FOREIGN KEY (PRODUCTID) REFERENCES Product(PRODUCTID)
);

--      Indexes
-- Reference
CREATE INDEX FK_User
ON User (GENDERID);

CREATE INDEX FK_Product
ON Product (BRANDID, TYPEID, GENDERID);

CREATE INDEX FK_Wishlist
ON Wishlist (PRODUCTID, COLORID, USERID, SIZEID);

CREATE INDEX FK_Cart
ON Cart (PRODUCTID, COLORID, USERID, SIZEID);

CREATE INDEX FK_Color_Product
ON Color_Product (COLORID, PRODUCTID);

CREATE INDEX FK_pImage_Product
ON pImage_Product (IMAGEID, PRODUCTID);

CREATE INDEX FK_Size_Product
ON Size_Product (SIZEID, PRODUCTID);


-- Unique
CREATE UNIQUE INDEX UK_Email
ON User (Email);

CREATE UNIQUE INDEX UK_Gender
ON Gender (gName);

CREATE UNIQUE INDEX UK_pImage
ON pImage (iName);

CREATE UNIQUE INDEX UK_Brand
ON Brand (bName);

CREATE UNIQUE INDEX UK_Color
ON Color (Hex, cName);

CREATE UNIQUE INDEX UK_pType
ON pType (tName);

CREATE UNIQUE INDEX UK_Size
ON Size (Size);
